### ISSUE TITLE
Solved it ! Turtlebot with Laserscanner

### ISSUE THREAD

**Issue by baeckermeister** [gergia/multiple_turtlebots_real_world#1]
Hi. I ran into the same Problem and after two day found a solution :)
First thing is, Frame_ids (generally) of the map from map_server must be "map" NOT "/map", because leading slash is removed by tf2. (see Migration guide, tf_prefix...). 
In my Launch-files I did not use param tf_prefix at top-Level and I also did not use the Group tag with Namespace. Is set ROS_NAMESPACE in bashrc. 
For Frame_ids I set it like this (example of amcl.launch)

```
<arg name="odom_frame_id"   default="$(env ROS_NAMESPACE)/odom"/>
<arg name="base_frame_id"   default="$(env ROS_NAMESPACE)/base_footprint"/>
<arg name="global_frame_id" default="map"/>
```

same in move_base:

```
<arg name="odom_frame_id"   default="$(env ROS_NAMESPACE)/odom"/>
<arg name="base_frame_id"   default="$(env ROS_NAMESPACE)/base_footprint"/>
<arg name="global_frame_id" default="map"/>
<arg name="odom_topic" default="odom" />
<arg name="laser_topic" default="scanInverted" />
<arg name="custom_param_file" default="$(find daniels)/param/dummy.yaml"/>
```

and in laserscan-Launch:

```
<node name="sick_tim571_2050101" pkg="sick_tim" type="sick_tim551_2050001" respawn="false">
   <param name="frame_id" type="str" value="$(env ROS_NAMESPACE)/laser" />
</node>
<node pkg="tf" type="static_transform_publisher" name="sick_tf" args="0 0 0 0 0 0 $(env ROS_NAMESPACE)/plate_top_link $(env ROS_NAMESPACE)/laser 100"/>
```

for Robot state Publisher

```
<node pkg="robot_state_publisher" type="robot_state_publisher" name="robot_state_publisher">
    <param name="publish_frequency" type="double" value="5.0" />
    <param name="tf_prefix" type="string" value="$(env ROS_NAMESPACE)"/>
  </node>
```

and for kobuki_node:

```
<node pkg="nodelet" type="nodelet" name="mobile_base" args="load kobuki_node/KobukiNodelet mobile_base_nodelet_manager">
    <rosparam file="$(find kobuki_node)/param/base.yaml" command="load"/>
    <param name="device_port" value="$(arg serialport)" />
    <param name="odom_frame" value="$(env ROS_NAMESPACE)/odom" />
    <param name="base_frame" value="$(env ROS_NAMESPACE)/base_footprint" />
    <remap from="mobile_base/odom" to="odom"/>
```

Update: Also check that there are no leading slashes in frame_ids in the move_base param-files

Did this help you ?

this is the tf-tree:

[frames.pdf](https://github.com/gergia/multiple_turtlebots_real_world/files/540841/frames.pdf)

**Comment by ivan-gavran** [comment]
great! I'll test it and write what happened (will have access to robots by Friday)

**Comment by ivan-gavran** [comment]
@baeckermeister, I get your idea: to exclude automatic handling of tf-prefixes and manually control them. However, I was not able to get it to work yet. 
It will take me some more time (as this week I am away again), but as soon as I get it to work, I will post here the code.
thanks again for your contribution :)

**Comment by baeckermeister** [comment]
@gergia OK. which Version do you use ? I use Kinetic. I also do not use (almost) the original turtlebot-launch files. I copied them into my package and checked, that there a no leading slashes anywhere except for the map-topic. One Thing I remember is, that also all nodelets from mobile_base had originally a leading slash in the arguments, but in turtlebot's repository I can't find it.hmm. perhaps they changed it.

I attached all my include-files. In my main Launch-file are no arguments. Everything is set in my include-files.

myPackage/launch/...
[launch.txt](https://github.com/gergia/multiple_turtlebots_real_world/files/568530/launch.txt)
myPackage/launch/includes/...
[includes.zip](https://github.com/gergia/multiple_turtlebots_real_world/files/568526/includes.zip)

My Setup: 
- 1 Master on an Laptop
- 4 Turtlebots with RaspberryPi3
- Everything with ROS Kinetic. 
- ROS_NAMESPACE set on each Turtlebot (PI3) like Robot1, Robot2 ... 
- Master has no Namespace 
- Mapserver is running on Master (that is why all map-topic-entries have a leading slash.
- all Frame-IDs have NO leading slash

What is the output of move_base ? I think something like "waiting for transform from X to map ..." ?

PS: did you add tf_prefix to robot_state_publisher when not using group and ns ? Or can you upload your testings without grouping into another branch?

**Comment by ivan-gavran** [comment]
@baeckermeister I completely missed this answer of yours. (I didn't let it hang because carelessness)
In the meantime I didn't manage to adapt my launch files so I will try to reuse yours now. My setup is almost the same except for running ROS Indigo instead of Kinetic.

What did you mean by the question _What is the output of move_base?_ ? For my case or are you telling me about your case?

**Comment by ivan-gavran** [comment]
So, @baeckermeister, I tried to use your solution in my context (at [this branch](https://github.com/gergia/multiple_turtlebots_real_world/tree/baeckermeisterSolution) ).

However, I still get the same error, and the same tree.

The differences between our two setups are  (and correct me if I am wrong):

- you are using sick_tim laser, I am using kinect (therefore, I had to add other files). Upon checking tf transforms that have to do with camera, they are all prefixed correctly
- you are using kinetic, I am using Indigo

**Comment by baeckermeister** [comment]
Hi,
if your setup still doesn't work, move_base (from your solution) should say sth. like waiting for transform from X to Y... .
As i can see in branch baeckermeisterSolution, you are using `<group ns="robot_0">` again.
When I used the group-tag, it didn't work for me, so I removed it and use ROS_NAMESPACE.

can you post your tf-tree when using Master and only one Robot ?

in amcl.launch.xml `<arg name="global_frame_id" default="/map"/> should be <arg name="global_frame_id" default="map"/>`

**Comment by ivan-gavran** [comment]
Hi :)

yes, it still outputs the same messages (as listed in the repository description) - namely, waiting for transform from robot_0/base_footprint to /map to become available. And - when watching closely, for the debug messages, it also says _robot_0/amcl: MessageFilter [target=robot_0/odom ]:_  _Added message in frame /camera_depth_frame at time 1462446392.094, count now 100._
(however, when I inspect frames, camera_depth_frame is prefixed properly. Don't know where does this come from).

No, I am not using group ns  - I left all the old file there (`robot_under_namespace.launch`), but I am using yours, launch_b.txt (added that comment to the repository description).

I changed the map to /map because I thought that might have been causing the troubles. It didn't help (now I changed it back, but the result is the same).

Finally, this is how the tf-tree looks like:
[frames.pdf](https://github.com/gergia/multiple_turtlebots_real_world/files/831089/frames.pdf)

**Comment by ivan-gavran** [comment]
An update: I managed to get it work. Aaron Miller solved the namespace problem in [the fork](https://github.com/amiller27/multiple_turtlebots_real_world) by remapping `camera_depth_frame` to namespace based one. However, he had some new bugs ([link](http://answers.ros.org/question/237671/high-cpu-usage-for-amcl-and-move_base-under-namespace/#256666)).

Based on this I tried to fix my adaptation of your idea the same way, but it didn't work out.

Nevertheless, now we have two solutions - yours (although I still didn't get it running) and the new one.
:+1:

**Comment by baeckermeister** [comment]
hi, glad it works now !
in branch baeckermeisterSolution you also need to change `<param name="output_frame_id" value="/$(arg camera)_depth_frame"/>` to use namespaces like in Aaron Miller's fork.

It then should work. The Launch/include-files I provided, are from my working solution...

Regarding your bugs, did gavran's answer solve it ?

We had some performance issues when using Kinect with the raspberrys. The more robots where active, streaming only rgb-video, the more timeout-messages we got. We think (we are not sure) this has to do with wifi, general ros logging, sd-card...

**Comment by ivan-gavran** [comment]
Yes, I've read about similar experiences (so people would move onto multi master solutions).

Actually, _gavran_ is my username on ROS Answers so yes, that was the solution.
After accepting Aaron pull-request, we have a working solution now. I got yours also running. 
Let me update the description of the repo, now that we have a success. Thanks a lot for your help.

**Comment by apletta** [comment]
Can you initialize more than one robot using the $(env ROS_NAMESPACE) technique? If so would it just involve making a second env variable i.e. ROS_NAMESPACE_2 ?

**Comment by ivan-gavran** [comment]
Hi @apletta !
I've been out of this problem for some years now. But on the high level: the idea was to initialize many robots, each having a different value for ROS_NAMESPACE. (and we are talking here about real Turtlebots). If you are interested in a simulation, then [this repository](https://github.com/gergia/multiple_turtlebots_stage_amcl) follows the same logic

**Comment by apletta** [comment]
Awesome! Looks promising, I'll check it out. Thanks!
