### ISSUE TITLE
Question about using this with RVIZ.

### ISSUE THREAD

**Issue by ghost** [gergia/multiple_turtlebots_real_world#3]
With the code as it is are you able to use the RVIZ '2D pose estimate' button to initialize the AMCL?

Given that the AMCL is working within the Namespace robot_0.  Do you have to send the initial pose message on /robot_0/initialpose or /initialpose?

Thanks,
Vikrant

**Comment by ghost** [comment]
I was able to address this by changing the following:
In file: multiple_turtlebots_real_world/launch/includes/single_robot_wild.launch - 
line 41:
I updated it to change /map to map as follows:

` <arg name="global_frame_id" value="/map"/>`

**Comment by ivan-gavran** [comment]
OK, I am coming late to this party :)
But help me understand what was you solution: you changed 
` <arg name="global_frame_id" value="/map"/>`

to

` <arg name="global_frame_id" value="map"/>`
?

Or?

**Comment by ghost** [comment]
Yep that is correct.  Apologies for the confusion.

**Comment by ghost** [comment]
Btw, did you ever get the mobile base working under namespace?  I could certainly use some tips for that...

**Comment by ivan-gavran** [comment]
why, but this codebase is the one that works under namespace... what kind of problems are you facing?

**Comment by ghost** [comment]
I had also put the map topic under namespace which broke some stuff including move_base.  I think I got it all sorted now.  The last little trick was that under the move_base node, I had to remap cmd_vel to cmd_vel_mux/input/navi like:
` <remap from="cmd_vel" to="cmd_vel_mux/input/navi"/>`
I am now able to run everything under namespace as well as under multi-master onto a different base station computer running a separate ROS core.

**Comment by ivan-gavran** [comment]
that's very good. Do you have a GIthub repo with a complete setup?
