### ISSUE TITLE
Dead link in README

### ISSUE THREAD

**Issue by jay3ss** [gergia/multiple_turtlebots_real_world#4]
The link to the `tf` tree is dead.

> Currently, the attempt to launch a single robot under namespace with amcl failed. The tf tree looks like [this](https://dl.dropboxusercontent.com/u/11955498/framesTurtlebotUnderNamespace.pdf).

**Comment by ivan-gavran** [comment]
thanks for noticing. (I can't access that file now, so as a quick fix I removed it from text). But, you do understand that was the case previously (this part of text was left for history) and that currently the problem is fixed and launching turtlebot under namespace is possible?

**Comment by jay3ss** [comment]
No, I didn't realize that because in the previous sentence says

> Currently, the attempt to launch a single robot under namespace with amcl failed.

But, I'm glad that you got it working. It's not a trivial task as I just did the same with two of my own robots.

**Comment by ivan-gavran** [comment]
So that others don't get confused, I removed the "historical notes" from the history. thanks for pointing out
