### ISSUE TITLE
I have the same problem!

### ISSUE THREAD

**Issue by tx0619s** [gergia/multiple_turtlebots_real_world#5]
Hi gergia,

I am also trying to figure out the same problem as you had about namespace for multi-turtlebots.

I followed your Solved it ! Turtlebot with Laserscanner post and modified my launch files based on baeckermeister solution. And now I have the same tf-tree as you had before, the tree has robot1/odom robot1/base_footprint and robot1/base_link all linked together but without map on the top. 

Could you let me know how you solve this? I would very appreciate it.

Forgot to mention, I use Ubuntu14.04 and Indigo. My camera is astra.

-----------------------
Now there are two map topics among all my topics , /map and /robot1/map.  /robot1/map has /robot1/map_server publisher but no subscriber. /map has /robot1/amcl subscriber but no publisher.

-----------------------
More specifically, how do you get robot1/amcl as broadcaster between map and robot1/odom?

**Comment by ivan-gavran** [comment]
Did you try to use the files the way there are in the master branch? I never managed to get baeckermeister's solution work for me, but did manage to get the whole system running (and that should be the situation in the master branch) by using [this fork](https://github.com/amiller27/multiple_turtlebots_real_world)

**Comment by tx0619s** [comment]
Thanks for your response!

I have found solution based on baeckermeister solution. The only trick thing I did is that I modified 3dsensor.launch file. I added namespace for output_frame_id in laserscan section. Having done this, everything works fine. 

Your post is very helpful and saved me a lot of time! Thank you very much!
